"""
Synthetic developer profiles for NEXUS prototype.
All data is fictional — no real personal information.
"""

DEVELOPER_PROFILES = [
    {
        "id": 1,
        "name": "Aarav Sharma",
        "role": "Android Developer",
        "skills": ["Kotlin", "Android", "Jetpack Compose", "Firebase"],
        "city": "Lucknow",
        "bio": "Building native Android apps with modern architecture patterns.",
        "recent_activity": "Spoke at Commudle Android Meetup — Sept 2026",
        # Private fields (never exposed via API)
        "email": "aarav.sharma@fake.dev",
        "phone": "+91-9000000001",
        "rsvp": "confirmed",
        "attendance": "present",
    },
    {
        "id": 2,
        "name": "Priya Verma",
        "role": "Flutter Developer",
        "skills": ["Flutter", "Dart", "Firebase", "REST APIs"],
        "city": "Lucknow",
        "bio": "Cross-platform mobile developer passionate about pixel-perfect UIs.",
        "recent_activity": "Led Flutter workshop at GDG Lucknow — Aug 2026",
        "email": "priya.verma@fake.dev",
        "phone": "+91-9000000002",
        "rsvp": "confirmed",
        "attendance": "present",
    },
    {
        "id": 3,
        "name": "Rohan Gupta",
        "role": "Backend Developer",
        "skills": ["Python", "FastAPI", "Django", "PostgreSQL"],
        "city": "Delhi",
        "bio": "Backend engineer focused on scalable API design.",
        "recent_activity": "Published FastAPI tutorial series — July 2026",
        "email": "rohan.gupta@fake.dev",
        "phone": "+91-9000000003",
        "rsvp": "waitlisted",
        "attendance": "absent",
    },
    {
        "id": 4,
        "name": "Sneha Iyer",
        "role": "Full-Stack Developer",
        "skills": ["React", "Node.js", "TypeScript", "MongoDB"],
        "city": "Bangalore",
        "bio": "Full-stack developer who loves building community tools.",
        "recent_activity": "Mentored at Commudle Hackathon — Sept 2026",
        "email": "sneha.iyer@fake.dev",
        "phone": "+91-9000000004",
        "rsvp": "confirmed",
        "attendance": "present",
    },
    {
        "id": 5,
        "name": "Vikram Patel",
        "role": "Android Developer",
        "skills": ["Android", "Java", "Kotlin", "Room DB"],
        "city": "Mumbai",
        "bio": "Experienced Android dev with 4+ years in production apps.",
        "recent_activity": "Open-sourced a Jetpack Compose UI kit — Aug 2026",
        "email": "vikram.patel@fake.dev",
        "phone": "+91-9000000005",
        "rsvp": "declined",
        "attendance": "absent",
    },
    {
        "id": 6,
        "name": "Ananya Reddy",
        "role": "ML Engineer",
        "skills": ["Python", "TensorFlow", "NLP", "LLMs"],
        "city": "Hyderabad",
        "bio": "Machine learning engineer working on NLP and large language models.",
        "recent_activity": "Presented LLM security research at AI Conf — Sept 2026",
        "email": "ananya.reddy@fake.dev",
        "phone": "+91-9000000006",
        "rsvp": "confirmed",
        "attendance": "present",
    },
    {
        "id": 7,
        "name": "Kabir Singh",
        "role": "Flutter Developer",
        "skills": ["Flutter", "Dart", "Android", "iOS"],
        "city": "Pune",
        "bio": "Mobile developer building beautiful cross-platform experiences.",
        "recent_activity": "Contributed to Flutter open-source plugins — July 2026",
        "email": "kabir.singh@fake.dev",
        "phone": "+91-9000000007",
        "rsvp": "confirmed",
        "attendance": "present",
    },
    {
        "id": 8,
        "name": "Meera Nair",
        "role": "DevOps Engineer",
        "skills": ["Docker", "Kubernetes", "CI/CD", "AWS"],
        "city": "Chennai",
        "bio": "DevOps specialist automating everything from build to deploy.",
        "recent_activity": "Hosted Kubernetes 101 webinar — Aug 2026",
        "email": "meera.nair@fake.dev",
        "phone": "+91-9000000008",
        "rsvp": "waitlisted",
        "attendance": "absent",
    },
    {
        "id": 9,
        "name": "Arjun Mehta",
        "role": "Android Developer",
        "skills": ["Android", "Kotlin", "Jetpack", "Compose"],
        "city": "Lucknow",
        "bio": "Android enthusiast building apps for local communities.",
        "recent_activity": "Won Best App award at Lucknow Hackathon — Sept 2026",
        "email": "arjun.mehta@fake.dev",
        "phone": "+91-9000000009",
        "rsvp": "confirmed",
        "attendance": "present",
    },
    {
        "id": 10,
        "name": "Diya Kapoor",
        "role": "UI/UX Designer",
        "skills": ["Figma", "React", "CSS", "Design Systems"],
        "city": "Delhi",
        "bio": "Designer-developer hybrid creating intuitive user experiences.",
        "recent_activity": "Redesigned Commudle community dashboard — Aug 2026",
        "email": "diya.kapoor@fake.dev",
        "phone": "+91-9000000010",
        "rsvp": "confirmed",
        "attendance": "present",
    },
]

# Public fields that are safe to expose
PUBLIC_FIELDS = {"id", "name", "role", "skills", "city", "bio", "recent_activity"}

# Private fields — NEVER expose
PRIVATE_FIELDS = {"email", "phone", "rsvp", "attendance"}
